Introduce satellite-relay
Summary:
- This will be used to relay HMC events to other dbus services within the BMC, making them accessible to BMC clients
- To start with, we just subscribe to Redfish events from any satellite controller that's present and relay them to `phosphor-logging` (`xyz.openbmc_project.Logging`)
- Then, BMC clients can access the events through the standard `bmcweb` redfish event service or through BMC event subscriptions.

[Using Rust in OpenBMC firmware](https://www.internalfb.com/wiki/OpenBMC/Rust/)

Test Plan:
```toml
# ~/.cargo/config.toml
[http]
proxy = "fwdproxy:8080"

[https]
proxy = "fwdproxy:8080"

[alias]
bmc = "build --target=armv7-unknown-linux-musleabihf --release --config profile.release.strip=true"
runbmc = "run --target=armv7-unknown-linux-musleabihf --release --config profile.release.strip=true"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnu-ld"
runner = "runbmc"
```
```bash
#!/bin/bash
# Add this to `~/.local/bin/runbmc`, and `chmod +x ~/.local/bin/runbmc`

set -euo pipefail

src="$1"
dst="/tmp/$(basename $1)"

rsync -vz -e ssh $src root@$RTPTEST_HOST:$dst
ssh -t root@$RTPTEST_HOST $dst
```
```bash
sudo dnf install -y binutils-arm-linux-gnu
```
```bash
cd ~/meta-openbmc/meta-facebook/meta-catalina/recipes-catalina/satellite-relay/files
export RTPTEST_HOST=rtptest243-oob.nha6
cargo runbmc
```

Start receiving and logging events like this:

```
Received an event: {
  "odata.type": "#Event.v1_4_0.Event",
  "Events": [
    {
      "Context": "satellite-relay",
      "EventId": "TestID",
      "EventTimestamp": "2025-01-05T09:21:30+00:00",
      "EventType": "Event",
      "MemberId": 0,
      "Message": "Generated test event",
      "MessageArgs": [],
      "MessageId": "OpenBMC.0.2.TestEventLog",
      "Severity": "OK"
    }
  ],
  "Id": "1",
  "Name": "Event Log"
}
Created log entry /xyz/openbmc_project/logging/entry/820
```

```
root@rtptest243-oob:~# busctl get-property xyz.openbmc_project.Logging /xyz/openbmc_project/logging/entry/820 xyz.openbmc_project.Logging.Entry AdditionalData
as 7 "Context=\"satellite-relay\"" "EventId=\"TestID\"" "EventTimestamp=\"2025-01-05T09:21:30+00:00\"" "EventType=\"Event\"" "MemberId=0" "MessageArgs=[]" "MessageId=\"OpenBMC.0.2.TestEven
tLog\""
```

Some examples of actual HMC events being received:

{P1708649973}

# Flash image size

This increases the flash image size by 1.2MB. We use 128MB flash devices but only reserve 86MB for the base filesystem (the other 42MB are for u-boot, the kernel, and  32MB of persistent storage), so this daemon is effectively consuming 1.4% of the image capacity.

```
$ ls -l ~/*.catalina.mtd
-rw-r--r-- 1 pdel users 52863272 Jan 13 20:54 /home/pdel/after.catalina.mtd
-rw-r--r-- 1 pdel users 51591496 Jan 13 20:53 /home/pdel/before.catalina.mtd
```
```
root@rtptest248-oob:~# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 08000000 00010000 "bmc"
mtd1: 000e0000 00010000 "u-boot"
mtd2: 00020000 00010000 "u-boot-env"
mtd3: 00900000 00010000 "kernel"
mtd4: 05600000 00010000 "rofs"
mtd5: 02000000 00010000 "rwfs"
mtd6: 08000000 00010000 "alt-bmc"
```
```
>>> (52863272 - 51591496) / 1024**2
1.212860107421875
>>> (52863272 - 51591496) / 0x05600000
0.014103024504905524
```

# Testing subscription errors

We want to try to handle subscription errors gracefully, so I've tested this by trigging HMC reset while running the service:

```
Error: Unable to ensure subscription to events from http://172.31.13.251/

Caused by:
    0: error sending request for url (http://172.31.13.251/redfish/v1)
    1: client error (Connect)
    2: tcp connect error: Network unreachable (os error 101)
    3: Network unreachable (os error 101)
```

After this, the systemd unit restarts (because the process exits with a non-zero exit code), and will keep restarting until the HMC is available again.

We can gracefully handle HMC presence once the GPIO monitoring is setup.

# Unit tests

{P1713829430}

# Lints

```
$ cargo clippy
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.14s
```

# On `rtptest248-oob.nha6`

Installed an image I built from my devserver and verified the service starts correctly and receives events:

```
root@rtptest248-oob:~# systemctl status xyz.openbmc_project.SatelliteRelay.service
● xyz.openbmc_project.SatelliteRelay.service - Start satellite management controller (SMC) event relay
     Loaded: loaded (/usr/lib/systemd/system/xyz.openbmc_project.SatelliteRelay.service; enabled; preset: enabled)
     Active: active (running) since Thu 2025-01-16 15:27:18 PST; 54min ago
 Invocation: ebdd4d55d4014831b084eb025f6352c3
   Main PID: 834 (satellite-relay)
        CPU: 1.324s
     CGroup: /system.slice/xyz.openbmc_project.SatelliteRelay.service
             └─834 /usr/bin/satellite-relay --from=http://172.31.13.251 --bind=http://172.31.13.241:8888
```
```
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]: 2025-01-17T00:20:19.419381Z  INFO satellite_relay: {
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:   "odata.type": "#Event.v1_9_0.Event",
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:   "Events": [
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:     {
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:       "EventTimestamp": "2025-01-17T00:19:26+00:00",
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:       "EventType": "Event",
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:       "LogEntry": {
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:         "odata.id": "/redfish/v1/Systems/HGX_Baseboard_0/LogServices/EventLog/Entries/23186"
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:       },
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:       "Message": "Device 'HGX_FW_CPU_0' successfully updated with image 'F0N_2A04'.",
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:       "MessageArgs": [
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:         "HGX_FW_CPU_0",
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:         "F0N_2A04"
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:       ],
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:       "MessageId": "Update.1.0.UpdateSuccessful",
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:       "MessageSeverity": "OK",
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:       "Oem": {
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:         "Nvidia": {
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:           "odata.type": "#NvidiaEvent.v1_0_0.EventRecord",
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:           "Device": "",
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:           "ErrorId": ""
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:         }
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:       }
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:     }
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:   ],
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:   "Id": "31",
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]:   "Name": "Event Log"
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]: }
Jan 16 16:20:19 rtptest248-oob.nha6.facebook.com satellite-relay[834]: 2025-01-17T00:20:19.431100Z  INFO satellite_relay: Created log entry /xyz/openbmc_project/logging/entry/1609
```

Reviewed By: williamspatrick

Differential Revision: D67543668

fbshipit-source-id: f8429a5c6ec09d6c797ac409072240999c753e6e